from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CardViewSet, ScenarioViewSet, AdventureViewSet, AdventureTurnViewSet, GlobalSettingsViewSet, ModelInputLimitViewSet, DefaultModelsViewSet

router = DefaultRouter()
router.register(r'cards', CardViewSet)
router.register(r'scenarios', ScenarioViewSet)
router.register(r'adventures', AdventureViewSet)
router.register(r'adventureturns', AdventureTurnViewSet)
router.register(r'global-settings', GlobalSettingsViewSet, basename='global-settings')
router.register(r'model-input-limits', ModelInputLimitViewSet, basename='modelinputlimit')
router.register(r'default-models', DefaultModelsViewSet, basename='default-models')

urlpatterns = [
    path('', include(router.urls)),
    # The URLs for custom actions are automatically generated by the router
]
