# Generated by Django 5.2.8 on 2026-05-27 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('platform', 'Platform'), ('user', 'User')], max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('custom', 'Custom')], max_length=32)),
                ('protocol', models.CharField(choices=[('openai_chat_completions', 'OpenAI Chat Completions'), ('openai_responses', 'OpenAI Responses'), ('anthropic_messages', 'Anthropic Messages'), ('gemini', 'Gemini'), ('litellm_native', 'LiteLLM Native')], default='openai_chat_completions', max_length=64)),
                ('base_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('platform', 'Platform'), ('user', 'User')], max_length=16)),
                ('display_name', models.CharField(max_length=160)),
                ('model_id', models.CharField(max_length=240)),
                ('context_window', models.PositiveIntegerField(default=32768)),
                ('user_context_limit_default', models.PositiveIntegerField(default=32768)),
                ('visible_response_target_tokens', models.PositiveIntegerField(default=350)),
                ('provider_safety_max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0.9)),
                ('top_p', models.FloatField(default=0.95)),
                ('frequency_penalty', models.FloatField(blank=True, null=True)),
                ('presence_penalty', models.FloatField(blank=True, null=True)),
                ('thinking_enabled', models.BooleanField(default=False)),
                ('thinking_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('show_thinking_default', models.BooleanField(default=False)),
                ('stream_thinking_default', models.BooleanField(default=False)),
                ('extra_parameters', models.JSONField(blank=True, default=dict)),
                ('additional_system_prompt', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to=settings.AUTH_USER_MODEL)),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_configs', to='ai_providers.providerconnection')),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('platform', 'Platform'), ('user', 'User')], max_length=16)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth', 'OAuth'), ('env', 'Environment')], default='api_key', max_length=16)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('env_var_name', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to=settings.AUTH_USER_MODEL)),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='ai_providers.providerconnection')),
            ],
            options={
                'ordering': ['provider_connection', 'display_name', 'created_at'],
            },
        ),
    ]
