# Generated by Django 5.2.2 on 2025-06-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceScenarioName', models.CharField(max_length=255)),
                ('adventureName', models.CharField(max_length=255)),
                ('scenarioSnapshot', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastPlayedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keys', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=5)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('actionType', models.CharField(blank=True, choices=[('say', 'Say'), ('do', 'Do'), ('story', 'Story')], max_length=5, null=True)),
                ('tokenUsage', models.JSONField(blank=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventureHistory', to='api.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('plotEssentials', models.TextField()),
                ('authorsNotes', models.TextField()),
                ('openingScene', models.TextField()),
                ('playerDescription', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=10)),
                ('cards', models.ManyToManyField(related_name='scenarios', to='api.card')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='sourceScenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='api.scenario'),
        ),
    ]
