# Generated by Django 5.2.2 on 2025-06-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_reported_prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('api_reported_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('api_reported_thinking_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_system_instruction_block_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_scenario_instructions_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_plot_essentials_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_authors_notes_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_adventure_history_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_cards_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('precise_current_user_message_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_input_tokens_from_precise_sum', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='adventureturn',
            name='token_usage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tokenusagestats'),
        ),
    ]
