# Generated by Django 5.2.2 on 2025-06-06 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tokenusagestats_adventureturn_token_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_handling_strategy', models.CharField(choices=[('truncate', 'Truncate')], default='truncate', max_length=20)),
                ('allow_ai_thinking', models.BooleanField(default=False)),
                ('global_max_output_tokens', models.PositiveIntegerField(default=200)),
                ('selected_model', models.CharField(default='gemini-pro', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tokenusagestats',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokenusagestats',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
