# Generated by Django 5.2.8 on 2026-05-27 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('draft_hash', models.CharField(blank=True, max_length=64)),
                ('import_metadata', models.JSONField(blank=True, default=dict)),
                ('default_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_scenarios', to='ai_providers.modelconfig')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('change_note', models.TextField(blank=True)),
                ('frozen_hash', models.CharField(max_length=64)),
                ('import_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_versions_created', to=settings.AUTH_USER_MODEL)),
                ('default_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_versions', to='ai_providers.modelconfig')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['scenario', '-version_number'],
                'unique_together': {('scenario', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_modules', to='scenarios.scenario')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('card_type', models.CharField(default='concept', max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('trigger_words', models.JSONField(blank=True, default=list)),
                ('use_for_character_creation', models.BooleanField(default=False)),
                ('activation_mode', models.CharField(choices=[('always', 'Always'), ('triggered', 'Triggered'), ('manual', 'Manual'), ('disabled', 'Disabled')], default='triggered', max_length=16)),
                ('priority', models.IntegerField(default=100)),
                ('token_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_cards', to='scenarios.scenario')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ['sort_order', 'priority', 'title'],
            },
        ),
    ]
