# Generated by Django 5.2.8 on 2026-05-27 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_providers', '0001_initial'),
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forked_from_timeline_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('forked_from_state_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('forked_from_state_hash', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('current_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventures', to='ai_providers.modelconfig')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to=settings.AUTH_USER_MODEL)),
                ('parent_adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='adventures.adventure')),
                ('root_adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooted_forks', to='adventures.adventure')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adventures', to='scenarios.scenario')),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adventures', to='scenarios.scenarioversion')),
            ],
            options={
                'ordering': ['-last_played_at'],
            },
        ),
        migrations.CreateModel(
            name='AdventureSnapshotBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario_title', models.CharField(max_length=240)),
                ('scenario_description', models.TextField(blank=True)),
                ('scenario_tags', models.JSONField(blank=True, default=list)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('cards', models.JSONField(blank=True, default=list)),
                ('starting_model_config_id', models.UUIDField(blank=True, null=True)),
                ('opening_scene', models.TextField(blank=True)),
                ('import_metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_schema_version', models.PositiveIntegerField(default=1)),
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_base', to='adventures.adventure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdventureSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('source_range_metadata', models.JSONField(blank=True, default=dict)),
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='adventures.adventure')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='ai_providers.modelconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdventureTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('timeline_sequence', models.PositiveIntegerField()),
                ('state_sequence', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system_note', 'System Note')], max_length=16)),
                ('action_type', models.CharField(blank=True, choices=[('do', 'Do'), ('say', 'Say'), ('story', 'Story'), ('continue', 'Continue'), ('retry', 'Retry')], max_length=16)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='adventures.adventure')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='ai_providers.modelconfig')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdventureMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(default='global', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='adventures.adventure')),
                ('source_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_memories', to='adventures.adventureturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='forked_from_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forked_adventures', to='adventures.adventureturn'),
        ),
        migrations.CreateModel(
            name='PromptSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_intent', models.CharField(max_length=40)),
                ('state_sequence', models.PositiveIntegerField(default=0)),
                ('context_limit', models.PositiveIntegerField(default=0)),
                ('estimated_tokens_by_layer', models.JSONField(blank=True, default=dict)),
                ('included_modules', models.JSONField(blank=True, default=list)),
                ('activated_cards', models.JSONField(blank=True, default=list)),
                ('included_summary_ids', models.JSONField(blank=True, default=list)),
                ('included_memory_ids', models.JSONField(blank=True, default=list)),
                ('included_turn_range', models.JSONField(blank=True, default=dict)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_snapshots', to='adventures.adventure')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_snapshots', to='ai_providers.modelconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('retry_instruction', models.TextField(blank=True)),
                ('included_variant_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_variants', to='adventures.adventure')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_variants', to='ai_providers.modelconfig')),
                ('prompt_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_variants', to='adventures.promptsnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adventureturn',
            name='prompt_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='adventures.promptsnapshot'),
        ),
        migrations.CreateModel(
            name='ResponseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_groups', to='adventures.generationvariant')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_groups', to='adventures.adventure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='response_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adventures.responsegroup'),
        ),
        migrations.AddField(
            model_name='adventureturn',
            name='response_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='adventures.responsegroup'),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('visible_output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('model_id', models.CharField(blank=True, max_length=240)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='adventures.adventure')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='ai_providers.modelconfig')),
                ('prompt_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='adventures.promptsnapshot')),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='ai_providers.providerconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generationvariant',
            name='token_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_variants', to='adventures.tokenusage'),
        ),
        migrations.AddField(
            model_name='adventureturn',
            name='token_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='adventures.tokenusage'),
        ),
        migrations.CreateModel(
            name='AdventureStateEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_sequence', models.PositiveIntegerField()),
                ('timeline_sequence', models.PositiveIntegerField()),
                ('effective_from_timeline_sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_invalidated', models.BooleanField(default=False)),
                ('invalidated_by_operation_id', models.CharField(blank=True, max_length=120)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='adventures.adventure')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adventure_state_events', to=settings.AUTH_USER_MODEL)),
                ('source_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_state_events', to='adventures.adventureturn')),
            ],
            options={
                'ordering': ['timeline_sequence', 'state_sequence'],
                'unique_together': {('adventure', 'state_sequence'), ('adventure', 'timeline_sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='adventureturn',
            unique_together={('adventure', 'sequence'), ('adventure', 'timeline_sequence')},
        ),
    ]
